version: "3.3"
services:
  ms-user:
    container_name: ms-user
    image: ms-user:v1.0.0
    networks: 
      - redinterna
    ports: 
      - 5001:5000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-user.rule=Host(`ms-user.um.localhost`)"
      - "traefik.http.routers.ms-user.entrypoints=web"
      - "traefik.http.services.ms-user.loadbalancer.server.port=5000"

networks:
  redinterna:
    external: true